In [ ]:
import numpy as np

#1
A = np.random.rand(5, 5)
A_einsum = np.einsum('ii->', A)
A_numpy = np.trace(A)
diff1 = np.linalg.norm(A_einsum - A_numpy)

#2
B = np.random.rand(5, 5)
AB_einsum = np.einsum('ij,jk->ik', A, B)
AB_numpy = np.dot(A, B)
diff2 = np.linalg.norm(AB_einsum - AB_numpy)

#3
first = np.random.rand(3, 4, 5)
second = np.random.rand(3, 5, 6)
einsum = np.einsum('ijk,ikl->ijl', first, second)
numpy = np.matmul(first, second)
diff3 = np.linalg.norm(einsum - numpy)

print("A_einsum: ", A_einsum, "\n")
print("A_numpy: ", A_numpy, "\n")
print("Diff: ", diff1, "\n\n")

print("A_einsum: ", AB_einsum, "\n")
print("A_numpy: ", AB_numpy, "\n")
print("Diff: ", diff2, "\n\n")

print("einsum: ", einsum, "\n")
print("numpy: ", numpy, "\n")
print("Diff: ", diff3)

A_einsum:  3.1140889727808325 

A_numpy:  3.1140889727808325 

Diff:  0.0 


A_einsum:  [[0.50761207 0.81302028 0.87979608 0.59148936 0.84560596]
 [0.60483    1.05424765 0.34118848 0.40960392 0.52280119]
 [1.25844341 1.72994241 1.55304393 1.2198013  1.68738648]
 [1.36458669 1.98345353 1.95771633 1.61914343 2.09835346]
 [0.64491508 0.96707925 0.4940578  0.55631997 0.72117949]] 

A_numpy:  [[0.50761207 0.81302028 0.87979608 0.59148936 0.84560596]
 [0.60483    1.05424765 0.34118848 0.40960392 0.52280119]
 [1.25844341 1.72994241 1.55304393 1.2198013  1.68738648]
 [1.36458669 1.98345353 1.95771633 1.61914343 2.09835346]
 [0.64491508 0.96707925 0.4940578  0.55631997 0.72117949]] 

Diff:  0.0 


einsum:  [[[0.81254004 1.0455103  1.28609626 1.13885994 1.7266988  0.89643037]
  [0.26781489 0.32063534 0.3084309  0.513428   0.61786485 0.63043506]
  [0.74578147 0.70112508 0.92505916 0.7646015  1.49263762 0.72193682]
  [0.65971247 0.71231719 0.78518012 1.00149967 1.53008102 1.23907832]]

 [[1.477717